[theme]
base                   = "light"
primaryColor           = "#0273e5"
backgroundColor        = "#EFEFEF"
secondaryBackgroundColor = "#FFFFFF"
textColor              = "#0C1214"
font                   = "sans serif"
